prenom = input("Entrez votre prenom :")
nom = input("Entrez votre nom :")
age = input("Entrez votre age :")
taille = input("Entrez votre taille :")
fruits_preferes = input("Listez vos fruits preferes :")
message_perso = input("Entrez un message personnalise :")
produit = input("Ajoutez un produit :")
prix_produit = input("Ajoutez un prix a votre produit :")

print("----------")
print("Bonjour,", prenom + " " + nom.upper())
print("Votre age :", age)
print("Votre taille :" , taille + "cm")
print("Vos fruits preferes :", fruits_preferes)
print("Votre message personnalise :", message_perso)
print("Votre produit :", produit)
print("Le prix de votre produit :", prix_produit + "€")